### ISSUE TITLE
How does this apply to derivative works?

### ISSUE THREAD

**Issue by ioistired** [kemitchell/icepick#1]
It's a very interesting license! It reminds me of your Killjoy series on your blog. I read through it and I can't figure out what happens to software built upon Icepick-licensed software, though.
Judging by "Software: all source code, tools, configuration, and other material used to run the software for the user", this would imply code that imports the licensed code, but it's not super clear to me.

**Comment by kemitchell** [comment]
@bmintz, thanks for your question!

Frankly, it's kind of a strange one: How does a software license apply to derivative works? I think it's safe to say that coders and other folk who don't know Copyright Act section numbers by heart probably wouldn't ask such a question if not for GPL. GPL goes way out of its way to express its rules in terms like "derivative work", even though those terms aren't particularly clear, and were less clear back when GPL came out.

Let's take a simple case: library under Icepick, built into an application. If a user of the application requests source code and permission, the application developer has to oblige. Likewise for a framework. Making an application built on a framework available to users entails building on and sharing the framework.

**Comment by ioistired** [comment]
So they have to provide source code (and other supporting data) for the application, but the license doesn't "spread"? So, for instance, a BlueOak licensed application can incorporate an Icepick library as long as the site operators also comply with Icepick wrt the entire application?

**Comment by kemitchell** [comment]
Icepick requires Icepick terms for source code:

> -  _Permission_:  On request, each user must be given the permission they need to exercise autonomy and independence.  For software, that means permission under these terms.

**Comment by ioistired** [comment]
Ah, thanks.
