### ISSUE TITLE
clarify moderation and the Noninterference clause

### ISSUE THREAD

**Issue by boringcactus** [kemitchell/icepick#2]
if I have a social media platform released under the Icepick license, the ability to moderate that platform is important. but as written, it looks like the Noninterference clause could be interpreted to prevent moderating a social platform, since this technically interferes with users' autonomy. I think the Icepick license is cool, but I also don't want to make content moderation against the rules. could this section be rephrased to eliminate this issue?

**Comment by kemitchell** [comment]
Thanks for this issue!

I don't mean to bury us in semantic details. But I do think it's important to ask: What do you mean by "moderation"? I do think there's a difference under the terms between rules or features that make it _impossible_ to post or share particular content and rules or features that make it possible to flag and hide particular content. In other words, I don't think noninterference prohibits using moderation, filtering, muting, or similar features.

**Comment by boringcactus** [comment]
i think drawing a distinction between broad automatic content filtering and manual (or narrowly targeted automatic) content removal is probably the way to go there. i definitely don't think it's intended to do that, but i think as phrased it could be reasonably interpreted to do that.

**Comment by kemitchell** [comment]
@boringcactus if at all possible, I'd like to keep the license clear in general terms, rather than write in specific edge-cases for specific questions.

I need to circle back and read the license terms again. But if you have time, might you quote the bit that you fear is prohibiting what you have in mind, and quote it for me. That way I can make sure I'm reading the same was that you are.

**Comment by boringcactus** [comment]
well the part that had me concerned was

> _Noninterference_: Users must be allowed to exercise autonomy and independence without technical, practical, legal, or other interference.

in conjunction with
> _Autonomy_: Each user must have the same ability to run, study, change, build on, and share this software.

but if the Autonomy clause doesn't specify that users must have an *unlimited* ability to run etc the software, then there's not actually an issue.
